### ISSUE TITLE
Script does not run

### ISSUE THREAD

**Issue by 9wow** [s-thom/bg3-sounds-converter#1]
```
C:\Users\user\Documents\bg3-sounds-converter-main>python categoriser.py
  File "C:\Users\user\Documents\bg3-sounds-converter-main\categoriser.py", line 10
    wwizer_pyz = "C:\Users\user\Documents\WWISER\wwiser-20231005\wwiser.pyz"
                                                                                ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
```

**Comment by s-thom** [comment]
It looks to me like the backslashes in your paths haven't been escaped. There's two ways to fix this.

1. Replace backslashes (`\`) with two (`\\`) to escape them
2. Use a raw string instead `r"C:\Users\user\..."`

Since I might be revisiting this script in the somewhat-distant future, and this is a pretty easy mistake to make, I'll make a note change the strings to raw strings (which don't treat backslashes specially). Hopefully that'll help the next person who comes along.

**Comment by DoggySmalls** [comment]
I've been trying to get this script to work and have downloaded all the required stuff and have set the proper file paths yet when I double click the python script I get a bunch of errors back to back. Don't suppose someone has all the sounds extracted already and has them categorized?

**Comment by DoggySmalls** [comment]
> It looks to me like the backslashes in your paths haven't been escaped. There's two ways to fix this.
> 
>     1. Replace backslashes (`\`) with two (`\\`) to escape them
> 
>     2. Use a raw string instead `r"C:\Users\user\..."`
> 
> 
> Since I might be revisiting this script in the somewhat-distant future, and this is a pretty easy mistake to make, I'll make a note change the strings to raw strings (which don't treat backslashes specially). Hopefully that'll help the next person who comes along.

For example do you mean like this? 
wwizer_pyz = "C:\\Users\\Kodii\\Desktop\\Mods\\BG3 Audio Extraction\\Wwizer wwnames"

**Comment by DoggySmalls** [comment]
![image](https://github.com/s-thom/bg3-sounds-converter/assets/165232125/a7336bd1-c44b-4395-b74a-9d43758c4408)

**Comment by DoggySmalls** [comment]
![image](https://github.com/s-thom/bg3-sounds-converter/assets/165232125/2107e93a-2218-4bbb-b272-5a8dcb2ee176)

**Comment by s-thom** [comment]
@DoggySmalls Can you try with folders that don't have spaces in the names? It might be sensitive to that, and I never tested what would happen if there were spaces in the folder names.

**Comment by DoggySmalls** [comment]
> @DoggySmalls Can you try with folders that don't have spaces in the names? It might be sensitive to that, and I never tested what would happen if there were spaces in the folder names.

Ey you're my hero. I think its working. Cheers, boss!

**Comment by DoggySmalls** [comment]
![image](https://github.com/s-thom/bg3-sounds-converter/assets/165232125/1fb3bdfb-5588-4a82-bea5-454b29027735)

**Comment by DoggySmalls** [comment]
Am I missing something or are they categorized in a certain way? Should the sounds be separated into different folders or are they all plopped into the destination folder. Like If I'm looking for Displacer Beast sounds do I have to search through all of these or is there a way I can narrow down my search to just ones labeled as animal noise and so on?

**Comment by 9wow** [comment]
@s-thom 
> 1. Replace backslashes (`\`) with two (`\\`) to escape them.

 Of course, the ONE thing I didn't try is actually the solution 😂 thank you.

**Comment by DoggySmalls** [comment]
> @s-thom
> 
> > 1. Replace backslashes (`\`) with two (`\\`) to escape them.
> 
> Of course, the ONE thing I didn't try is actually the solution 😂 thank you.

are they categorized for you tho?

**Comment by s-thom** [comment]
@9wow Glad it works!

@DoggySmalls Unfortunately, no. I tried having a dig around in the files to see if there were references to more human-friendly names when putting this script together, and couldn't find any. There may be something in other files in the game, but I don't know where to even start with that.

My use-case was just finding music files, which due to their length are larger in filesize, so I could rougly filter them out by that. Shorter sounds, such as those you're looking for, will probably be much harder to find unfortunately.

I did make a note on this in the README that you'd just have numbers, but it is at the end of the file and perhaps should be more prominent.

> 7. Your audio files will be categorised in the converted folder.
>     * The file names will be numbers, not human friendly names. If you are looking for something specific, then you will need to sort through them manually.

**Comment by s-thom** [comment]
Since it seems like both of you are able to run the script, I'm going to close the issue for now.

**Comment by 9wow** [comment]
@DoggySmalls 

> categorized 

Yes, it was categorised after running the script. 
Late response sorry.

**Comment by s-thom** [comment]
Hi @DoggySmalls, just a quick update. I ended up coming across [another GitHub repo](https://github.com/HumansDoNotWantImmortality/bg3-sids/wiki) that has most of the mappings from the sound ID numbers to the names in-game. I'm glad they figured out how to do it, because I never would have.

Anyway, I've updated the script to add a new step at the end to rename the files. There are some extra steps you have to do to set it up, unfortunately, as most of the filenames of the wiki pages have invalid characters in them.

But, it works, and there's 90 displacer beast idle sounds, and the attacks are probably somewhere in the spells folder but I haven't looked through that yet.

![image](https://github.com/s-thom/bg3-sounds-converter/assets/7552536/40bf765e-f325-4a93-af4f-c1c9c291159e)

If you have any issues running the script itself, just create a new issue.
