### ISSUE TITLE
Renaming Functionally not working

### ISSUE THREAD

**Issue by AlternatePFG** [s-thom/bg3-sounds-converter#2]
Hello. I'm having troubles getting the renaming functionality to work. I used WSL to download the .git repository, and then ran the command, but I'm not sure what it is really supposed to look like. 

![image](https://github.com/s-thom/bg3-sounds-converter/assets/12010125/507aa35f-6291-43b3-a969-72444df19fb9)

I get this popping up when I try to run the file, and then when I ran the script to make all the sounds .wav files, they were not renamed. I'm probably just missing something obvious, but I was wondering if you had any ideas. Thank you.

![image](https://github.com/s-thom/bg3-sounds-converter/assets/12010125/257e45ba-eb45-4024-a4b4-730bf91f6c30)

**Comment by s-thom** [comment]
Those filenames in WSL look correct to me. 

---

```py
wwizer_pyz = "F:\\BG3Sounds\\WWizer"
```

Just confirming, is this pointing to the `wwizer.pyz` file itself (just renamed), or is it pointing to a folder containing the `.pyz` and `.db3`? Because I just hacked together this script for myself, it's a bit janky and these two files actually need to be in the root of the repository instead. What I'm guessing happened was that the command it was running failed, but I didn't add any error handling so it just silently failed.

![image](https://github.com/s-thom/bg3-sounds-converter/assets/7552536/9dc531a6-61fe-4c52-8e51-186ff5700811)

With that you're probably looking at a value like:

```py
wwizer_pyz = "F:\\BG3Sounds\\wwizer.pyz"
```

Since the first step of the script seems to have completed successfully, you should also be able to set `should_convert = False` to save yourself some time (it'll still take a while to complete the rest of the steps).

**Comment by AlternatePFG** [comment]
It seems like you were right, and the wwiser was in the wrong place, but now I placed it in the same place and it seems like it silently failed as well, by your estimation. Here's a GIF of what it looked like

https://github.com/s-thom/bg3-sounds-converter/assets/12010125/f323d756-ee46-41bb-a803-8fe9f907a71e
![image](https://github.com/s-thom/bg3-sounds-converter/assets/12010125/7a7b45f1-69a3-4780-a6d7-8d31e027719d)



The first step did definitely work, but I don't think anything is working after that step.

![image](https://github.com/s-thom/bg3-sounds-converter/assets/12010125/171d74c1-4676-4180-a6a9-e837fda74126)

**Comment by s-thom** [comment]
Yeah, it's definitely failing if it's going that fast...

I'm going to be annoyed if this is the case, but reading your comments I realised I've been calling it `wwizer` with a Z instead of `wwiser` with an S. I've even mispelled it in the code of the script, despite knowing that the audio system is called [Wwise](https://www.audiokinetic.com/wwise/overview/) and not Wwize. Apparently my brain turned off there.

Anyway, what might've happened is that in my previous reply I said "oh yeah, set the value to `"F:\\BG3Sounds\\wwizer.pyz"`" (notice the Z), which is not the actual filename. Even though it's a simple misspelling, I hope that's what's causing the problem because if it's not I really have no idea.

**Comment by AlternatePFG** [comment]
Strange, I did just change it back to wwiser.pyz  
![image](https://github.com/s-thom/bg3-sounds-converter/assets/12010125/3acccffb-26da-4bd8-a83f-eac3c7fdd216)
But it seems like it has the same effect. It looks identical  to the previously sent GIF, unfortunately. 

I'm assuming this looks correct?
![image](https://github.com/s-thom/bg3-sounds-converter/assets/12010125/3f06e9a3-2dcc-4bb8-b1b9-3c3cc5430321)

![image](https://github.com/s-thom/bg3-sounds-converter/assets/12010125/2c606cb2-8793-419a-8897-e63509e053b1)


If so, I'm not entirely sure what the issue is unfortunately.

**Comment by s-thom** [comment]
Yeah, those look good. The script hasn't reached the point where those files are relevant yet, unfortunately. At this stage I don't really know what's going wrong, so I'm trying to think of what might cause it to fail.

Can you try commenting out or deleting lines 53 and 54, which should show the output of the wwiser commands. If it's working correctly, you should see something like 
![image](https://github.com/s-thom/bg3-sounds-converter/assets/7552536/4846fe2d-750a-4e0f-9456-f381192d1184)

If `wwizer_pyz` isn't set to the right thing, then you'll probably see
![image](https://github.com/s-thom/bg3-sounds-converter/assets/7552536/1c1813d4-b123-46d5-aa31-12cf34ceca2e)

If you get something else, then that's interesting and hopefully the logs have more to say.

**Comment by AlternatePFG** [comment]
![image](https://github.com/s-thom/bg3-sounds-converter/assets/12010125/c30a02ee-346b-4deb-b9e7-274fa764c925)
On the bright side, it's probably the problem? But I'm not sure why it's not working. I downloaded Python, maybe it's the shortcut issue its saying?

**Comment by s-thom** [comment]
Oh, that looks like the horrible alias that Microsoft includes to try get you to download Python through the store . It adds itself to the `PATH` so that typing `python` runs that, but it should be removed when installing Python. 

I'd recommend disabling the shortcut in settings, like in the second half of the message, then opening a new terminal window and running `python --version` to make sure it's actually pointing to the Python you installed. If you're still not seeing Python installed, install it again? Maybe?

**Comment by AlternatePFG** [comment]
It indeed was an issue with Python! It took me so long to respond because it was working its magic. This is a great script, my friend. Thank you for the timely responses. I'm not really familiar with Python/WLS/Linux or coding of any sort, really, so I definitely appreciate your help!

Getting help from someone so knowledgeable and intelligent in these matters is wonderful. Thanks a ton, my man.

It is all renamed. A few things weren't renamed, but the vast majority of it was, and now it's definitely legible! This was much appreciated, I plan on using these sounds for FoundryVTT/D&D purposes.

Thank you, again.
